
name: Build master

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  check_source:
    name: "Run code checks"
    uses: ./.github/workflows/_shared-check.yaml

  build_binaries:
    name: "Build Dora"
    needs: [check_source]
    uses: ./.github/workflows/_shared-build.yaml
    with:
      ref: ${{ github.sha }}
      release: "snapshot"
      docker: true
      docker_repository: "ethpandaops/dora"
      docker_tag_prefix: "master"
      additional_tags: "['master','master-latest']"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  clone_docker_images:
    name: "Copy docker images"
    needs: [build_binaries]
    uses: ./.github/workflows/_shared-docker-clone.yaml
    with:
      source_repository: "ethpandaops/dora"
      target_repository: "pk910/dora-the-explorer"
      tags: "['master:unstable']"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_PK_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PK_TOKEN }}
  
  create_snapshot_release:
    name: Create snapshot release
    needs: [build_binaries]
    runs-on: ubuntu-latest
    steps:
    # download build artifacts
    - name: "Download build artifacts"
      uses: actions/download-artifact@v3

    # (re)create snapshot binary release
    - name: Update snapshot tag & remove previous snapshot release
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}          
        script: |
          try {
            var snapshotTag = "snapshot";
            var snapshotRelease = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: snapshotTag
            });
            if(snapshotRelease && snapshotRelease.data && snapshotRelease.data.tag_name == snapshotTag) {
              console.log("delete previous snapshot release");
              await github.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: snapshotRelease.data.id
              });
            }

            var snapshotRef = await github.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/" + snapshotTag
            });
            if(snapshotRef && snapshotRef.data && snapshotRef.data.ref) {
              if(snapshotRef.data.object.sha !== context.sha) {
                await github.git.updateRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/" + snapshotTag,
                  sha: context.sha,
                });
              }
            }
            else {
              await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/" + snapshotTag,
                sha: context.sha,
              });
            }
          } catch (e) {
            console.log(e)
          }
    - name: Create snapshot release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: "Dev Snapshot"
        tag_name: "snapshot"
        body: |
          ## Latest automatically built executables. (Unstable development snapshot)
          Built from master branch (commit: ${{ github.sha }})

          Please read the [wiki](https://github.com/pk910/dora/wiki) for setup / configuration instructions.

          ### Release Artifacts
          | Release File  | Description |
          | ------------- | ------------- |
          | [dora_snapshot_windows_amd64.zip](https://github.com/pk910/dora/releases/download/snapshot/dora_snapshot_windows_amd64.zip) | dora executables for windows/amd64 |
          | [dora_snapshot_linux_amd64.tar.gz](https://github.com/pk910/dora/releases/download/snapshot/dora_snapshot_linux_amd64.tar.gz) | dora executables for linux/amd64 |
          | [dora_snapshot_linux_arm64.tar.gz](https://github.com/pk910/dora/releases/download/snapshot/dora_snapshot_linux_arm64.tar.gz) | dora executables for linux/arm64 |
          | [dora_snapshot_darwin_amd64.tar.gz](https://github.com/pk910/dora/releases/download/snapshot/dora_snapshot_darwin_amd64.tar.gz) | dora executable for macos/amd64 |
          | [dora_snapshot_darwin_arm64.tar.gz](https://github.com/pk910/dora/releases/download/snapshot/dora_snapshot_darwin_arm64.tar.gz) | dora executable for macos/arm64 |
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # generate & upload release artifacts
    - name: "Generate release package: dora_snapshot_windows_amd64.zip"
      run: |
        cd explorer_windows_amd64
        zip -r -q ../dora_snapshot_windows_amd64.zip .
    - name: "Upload snapshot release artifact: dora_snapshot_windows_amd64.zip"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dora_snapshot_windows_amd64.zip
        asset_name: dora_snapshot_windows_amd64.zip
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: "Generate release package: dora_snapshot_linux_amd64.tar.gz"
      run: |
        cd explorer_linux_amd64
        tar -czf ../dora_snapshot_linux_amd64.tar.gz .
    - name: "Upload snapshot release artifact: dora_snapshot_linux_amd64.tar.gz"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dora_snapshot_linux_amd64.tar.gz
        asset_name: dora_snapshot_linux_amd64.tar.gz
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: "Generate release package: dora_snapshot_linux_arm64.tar.gz"
      run: |
        cd explorer_linux_arm64
        tar -czf ../dora_snapshot_linux_arm64.tar.gz .
    - name: "Upload snapshot release artifact: dora_snapshot_linux_arm64.tar.gz"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dora_snapshot_linux_arm64.tar.gz
        asset_name: dora_snapshot_linux_arm64.tar.gz
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: "Generate release package: dora_snapshot_darwin_amd64.tar.gz"
      run: |
        cd explorer_darwin_amd64
        tar -czf ../dora_snapshot_darwin_amd64.tar.gz .
    - name: "Upload snapshot release artifact: dora_snapshot_darwin_amd64.tar.gz"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dora_snapshot_darwin_amd64.tar.gz
        asset_name: dora_snapshot_darwin_amd64.tar.gz
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: "Generate release package: dora_snapshot_darwin_arm64.tar.gz"
      run: |
        cd explorer_darwin_arm64
        tar -czf ../dora_snapshot_darwin_arm64.tar.gz .
    - name: "Upload snapshot release artifact: dora_snapshot_darwin_arm64.tar.gz"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dora_snapshot_darwin_arm64.tar.gz
        asset_name: dora_snapshot_darwin_arm64.tar.gz
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}

  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optionally push to the Docker Hub (docker.io)
          # docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security
          # customize the username to be used when pushing to the Docker Hub
          # docker_io_user: foobar  # see https://github.com/macbre/push-to-ghcr/issues/14